services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo
    ports:
      - "80:5000"
    volumes:
      # Cant be mounted in dev container must ssh into host to mount this
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app:app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped